#!/bin/bash

#**********************************************
#          Metaplex Store Installer           *
# Created By: BlackRanger07                   *
# Copyright: BlackRanger07 - Oct 2021         *
#**********************************************

clear #Start the screen fresh.

#Reused variables
current_dir=$(pwd)
GITHUB=""
SITENAME=""
SITEPATH="${current_dir}/metaplex/js/packages/web/src"
asset_pfix_new="ASSET_PREFIX="
asset_pfix_old="ASSET_PREFIX=/metaplex/"
GRADIENT="background: linear-gradient(180deg, rgba(18, 18, 18, 0) 0%, @black-100 100%);"
NO_GRADIENT="background: linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%);"

#Functions Here
filechanges () {
  #Edit packages.json file at line 47
  clear
  #Change the owner name of the repository for Metaplex."
  sed -i 's/metaplex-foundation/'${GITHUB}'/g' ${current_dir}/metaplex/js/packages/web/package.json
  #Modify Asset Prefix in package.json line 56.
  sed -i "s|${asset_pfix_old}|${asset_pfix_new}|" ${current_dir}/metaplex/js/packages/web/package.json
  #Add wallet address in .env file.
  read -p "Paste the wallet address for the store owner: " WALLET
  cat > ${current_dir}/metaplex/js/packages/web/.env <<EOF
  REACT_APP_STORE_OWNER_ADDRESS_ADDRESS=${WALLET}
  REACT_APP_STORE_ADDRESS=
EOF
  #Add CNAME
  touch ${current_dir}/metaplex/js/packages/web/public/CNAME
  read -p "Enter your CNAME or website name that will point to github pages: " SITENAME
  echo ${SITENAME} > ${current_dir}/metaplex/js/packages/web/public/CNAME
}

#Error Checking
error_check () {
  if [ $? = 0 ]; then
    echo "Previous Change Succeeded..."
  else
    echo "Previous Change Failed!"
  fi
}

#Configure the site to the users liking.
site_renov () {
while [ ${CHANGES} != "Y" ] || [ ${CHANGES} != "y" ]; do
  read -p "What should the site name be? Default is Metaplex NFT Marketplace: " STORE
  read -p "For the ${SITENAME} Logo, paste the URL address where your Logo is hosted: " LOGO
  read -p "For the ${SITENAME} banner, paste the URL address where your banner is hosted: " BANNER
  read -p "Enter a heading for ${SITENAME}. This will replace <The amazing world of Metaplex.> " HEADING
  read -p "Enter a sub-Heading for ${SITENAME}. This will replace <Buy exclusive Metaplex NFTs.> " SUBHEAD
  clear
  read -p "Are you satisfied with your changes to [ ${SITENAME} ]?" CHANGES
  if [ ${CHANGES} = "y" ] || [ ${CHANGES} = "Y" ]; then
    sed -i "s|Metaplex NFT Marketplace|${STORE}|" ${SITEPATH}/src/pages/_app.tsx
    echo "Store Name: " error_check
    sed -i "s|Metaplex NFT Marketplace|${STORE}|" ${SITEPATH}/src/pages/_document.tsx
    echo "Store Name: " error_check
    sed -i "s|img src={'/metaplex-logo.svg'}|img src={'${LOGO}'}|" ${SITEPATH}/views/home/auctionList.tsx
    echo "Logo Link Installed: " error_check
    echo "Adjusting background size..."
    sed -i "s/background-size: 924px 100%;/background-size: 100% 100%;/" ${SITEPATH}/components/Banner/index.less
    echo "Background size adjustment: " error_check
    echo "Removing gradient from overshadowing banner..."
    sed -i "s/${GRADIENT}/${NO_GRADIENT}/" ${SITEPATH}/components/Banner/index.less
    echo "Gradient Removed: " error_check
    sed -i "s|/main-banner.svg|${BANNER}|" ${SITEPATH}/src/views/home/auctionList.tsx
    echo "Banner Link Added: " error_check
    sed -i "s/The amazing world of Metaplex./${HEADING}/" ${SITEPATH}/views/home/auctionList.tsx
    echo "Heading Changed: " error_check
    sed -i "s/Buy exclusive Metaplex NFTs./${SUBHEAD}/" ${SITEPATH}/views/home/auctionList.tsx
    echo "SubHeading Changed: " error_check
    sleep 3
    clear
    echo "The site will now be deployed. Have your github account and access code ready..."
    sleep 1
    yarn deploy
    echo "${SITENAME} has been configured to your specification."
  fi
done
}

#Clone the Metaplex Repo from the Users Github repository.
read -p "Enter your github name: " GITHUB
if [ ! -d ${current_dir}/metaplex ]; then
  git clone https://github.com/"${GITHUB}"/metaplex.git
fi

#START OF PROGRAM - Prerequisites for Metaplex Store to be installed.
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y curl
if [ $? = 0 ]; then
  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  if [ $? = 0 ]; then
    sudo apt install -y nodejs
  else
    clear
    echo "Nodejs did not download properly! Please Investigate."
    exit 1
  fi
else
  clear
  echo "Curl did not install! Please Investigate."
  exit 2
fi

#Run function to make the necessary file changes.
filechanges

#Setup npm, yarn and then deploy.
cd ${current_dir}/metaplex/js
npm install -g yarn
if [ $? = 0 ]; then
  echo "Yarn installed successfully!"
  yarn
  if [ $? = 0 ]; then
    yarn bootstrap
    if [ $? = 0 ]; then
      clear
      echo "Metaplex will now be built."
      yarn build
      if [ $? = 0 ]; then
        cd packages/web
        #Ask user if they have set their Github identity before, get info and set if not.
        read -p "Have you set your GitHub default identity? (y/N) " IDENTITY
        if [ ${IDENTITY} = "n" ] || [ ${IDENTITY} = "N" ]; then
          read -p "Enter your email address that is used for Github: " EMAIL
          read -p "Enter your Github User Name: " USER
          git config --global user.email "${EMAIL}"
          git config --global user.name "${USER}"
        fi
        if [ $? = 0 ]; then
          clear
          read -p "Would you like to make site modifications to ${SITENAME}? (Y/n)" CHOICE
          if [ ${CHOICE} = "y" ] || [ ${CHOICE} == "Y" ]; then
            site_renov
          else
            #Deploy the Metaplex site and Go Live.
            echo "Metaplex will now be deployed. Have your github account and access code ready."
            yarn deploy
          fi
          clear
          echo "************************************************************************"
          echo "  Your metaplex store is now ready to be used at: ${SITENAME}"
          echo "  If you found this installer helpful please support with SOL."
          echo ""
          echo "     Donate SOL: 9inpsvQZYiTekRJEuNBLjPjNoQzSCDx9iuHMq3uTzssB"
          echo "************************************************************************"
        fi
      else
          clear
          echo "The command (yarn build) had an issue, please investigate."
          exit 4
      fi
    fi
  fi
else
  clear
  echo "Yarn did not install, please investigate."
  exit 3
fi
