#!/bin/bash

#**********************************************
#          Metaplex Store Installer           *
# Created By: BlackRanger07                   *
# Copyright: BlackRanger07 - Oct 2021         *
#**********************************************

clear #Start the screen fresh.

#Reused variables
current_dir=$(pwd)
GITHUB=""
SITENAME=""
SITEPATH="${current_dir}/metaplex/js/packages/web/src"
GRADIENT="background: linear-gradient(180deg, rgba(18, 18, 18, 0) 0%, @black-100 100%);"
NO_GRADIENT="background: linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%);"

site_demo () {
  #Revert Changes so that user can make the proper changes in site renov function.
  echo "Reverting changes..."
  sed -i "s|${STORE}|Metaplex NFT Marketplace|" ${SITEPATH}/src/pages/_app.tsx
  error_check
  sed -i "s|${STORE}|Metaplex NFT Marketplace|" ${SITEPATH}/src/pages/_document.tsx
  error_check
  sed -i "s|img src={'${LOGO}'}|img src={'/metaplex-logo.svg'}|" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  sed -i "s/background-size: 100% 100%;/background-size: 924px 100%;/" ${SITEPATH}/components/Banner/index.less
  error_check
  echo "Adding gradient over banner..."
  sed -i "s/${NO_GRADIENT}/${GRADIENT}/" ${SITEPATH}/components/Banner/index.less
  error_check
  sed -i "s|${BANNER}|/main-banner.svg|" ${SITEPATH}/src/views/home/auctionList.tsx
  error_check
  sed -i "s/${HEADING}/The amazing world of Metaplex./" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  sed -i "s/${SUBHEAD}/Buy exclusive Metaplex NFTs./" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  clear
}

#Configure the site to the users liking.
site_renov () {
  read -p "What should the site name be? Default is Metaplex NFT Marketplace: " STORE
  sed -i "s|Metaplex NFT Marketplace|${STORE}|" ${SITEPATH}/src/pages/_app.tsx
  error_check
  sed -i "s|Metaplex NFT Marketplace|${STORE}|" ${SITEPATH}/src/pages/_document.tsx
  error_check
  #Site Logo address
  read -p "For the ${SITENAME} Logo, paste the URL address where your Logo is hosted: " LOGO
  sed -i "s|img src={'/metaplex-logo.svg'}|img src={'${LOGO}'}|" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  echo "Adjusting background size..."
  sed -i "s/background-size: 924px 100%;/background-size: 100% 100%;/" ${SITEPATH}/components/Banner/index.less
  error_check
  echo "Removing gradient from overshadowing banner..."
  sed -i "s/${GRADIENT}/${NO_GRADIENT}/" ${SITEPATH}/components/Banner/index.less
  error_check
  read -p "For the ${SITENAME} banner, paste the URL address where your banner is hosted: " BANNER
  sed -i "s|/main-banner.svg|${BANNER}|" ${SITEPATH}/src/views/home/auctionList.tsx
  error_check
  read -p "Enter a heading for ${SITENAME}. This will replace <The amazing world of Metaplex.> " HEADING
  sed -i "s/The amazing world of Metaplex./${HEADING}/" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  read -p "Enter a sub-Heading for ${SITENAME}. This will replace <Buy exclusive Metaplex NFTs.> " SUBHEAD
  sed -i "s/Buy exclusive Metaplex NFTs./${SUBHEAD}/" ${SITEPATH}/views/home/auctionList.tsx
  error_check
  clear
  read -p "Are you satisfied with your changes to [ ${SITENAME} ]?" CHANGES
  if [ ${CHANGES} = "y" ] || [ ${CHANGES} = "Y" ]; then
    clear
    echo "The site will now be deployed. Have your github account and access code ready..."
    sleep 1.5
    yarn deploy
    echo "${SITENAME} has been configured to your specification."
  elif [ ${CHANGES} = "n" ] || [ ${CHANGES} = "N" ]; then
    site_demo
  fi
}